### ISSUE TITLE
[NuGet] No error shown is NuGet package can't be added to project because of incompatibility

### ISSUE THREAD

**Issue by garuma** [Microsoft/workbooks#109] opened 2017-11-25 15:45 UTC
### Environment

```
[Info][00:00:22.3105140] MessageViewController (LogMessage): PushMessage => Status: Restoring packages… @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/Messages/MessageViewController.cs:125
[Info][00:00:22.4167320] InteractivePackageManager (.ctor): Enumerating NuGet source repositories @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:98
[Info][00:00:22.4340610] InteractivePackageManager (.ctor):     [Xamarin Internal] https://www.myget.org/F/xamarin-internal/auth/08bb9531-0ad8-40c5-ac0e-8618b863d416/api/v2 @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:91
[Info][00:00:22.4343050] InteractivePackageManager (.ctor):     [Official NuGet Gallery] https://www.nuget.org/api/v2/ (ignored) @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:91
[Info][00:00:22.4343640] InteractivePackageManager (.ctor):     [.NET Build Tools] https://www.myget.org/F/dotnet-buildtools/ (disabled) @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:91
[Info][00:00:22.4344940] InteractivePackageManager (.ctor):     [Android Designer Local] /Users/jeremie/mono/designer2/Xamarin.Designer.Android/Xamarin.AndroidDesigner/JavaAndroidDesigner/prebuilts @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:91
[Info][00:00:22.4346240] InteractivePackageManager (.ctor):     [GuiUnitNg Local] /Users/jeremie/projects/GuiUnitNg/GuiUnitNg/bin/Release @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:91
[Info][00:00:22.4348500] InteractivePackageManager (.ctor):     [nuget.org] https://api.nuget.org/v3/index.json (primary) @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:91
[Info][00:00:22.4962500] NuGet (Log): Restoring packages for /Users/jeremie/Library/Caches/com.xamarin.Workbooks/package-manager... @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Error][00:00:22.7792700] NuGet (Log): NU1202: Package MathNet.Numerics 3.20.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package MathNet.Numerics 3.20.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+sl5+win8 (.NETPortable,Version=v0.0,Profile=Profile47)
  - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
  - portable-net45+win8+wp8 (.NETPortable,Version=v0.0,Profile=Profile78)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:37.8062410] NuGet (Log): 
 @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:37.8075000] NuGet (Log): Attempting to gather dependency information for package 'MathNet.Numerics.3.20.0' with respect to project 'InteractiveNuGetProject', targeting '.NETCoreApp,Version=v2.0' @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:38.1626880] NuGet (Log): Gathering dependency information took 348.39 ms @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:38.1666040] NuGet (Log): Attempting to resolve dependencies for package 'MathNet.Numerics.3.20.0' with DependencyBehavior 'Lowest' @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:38.1966310] NuGet (Log): Resolving dependency information took 0 ms @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:38.1968750] NuGet (Log): Resolving actions to install package 'MathNet.Numerics.3.20.0' @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:38.1985410] NuGet (Log): Resolved actions to install package 'MathNet.Numerics.3.20.0' @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:38.2129710] NuGet (Log): Retrieving package 'MathNet.Numerics 3.20.0' from 'nuget.org'. @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:38.2494340] NuGet (Log): Successfully installed 'MathNet.Numerics 3.20.0' to InteractiveNuGetProject @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
[Info][00:00:38.2507860] NuGet (Log): Executing nuget actions took 44.14 ms @ /Users/builder/vsts/_work/11/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageLogger.cs:40
```

### Steps to Reproduce

1. Create a .NET core 2.0 workbook
2. Try to add https://www.nuget.org/packages/MathNet.Numerics (3.20.0)
3. Workbooks seems to add the package but in reality it's not added correctly

### Expected Behavior

Warn about the mismatch

### Actual Behavior

Silently fails

**Comment by sandyarmstrong** [comment] 2017-11-25 16:49
Essentially a dupe of https://github.com/Microsoft/workbooks/issues/25. Also see https://github.com/Microsoft/workbooks/issues/42.

**Closed by sandyarmstrong** 2017-11-25 16:49 UTC
