### ISSUE TITLE
"Error initializing android tools"

### ISSUE THREAD

**Issue by CatoCensor** [Microsoft/workbooks#140] opened 2017-12-17 10:23 UTC
### Steps to Reproduce

1. Open any workbook that targets Android

### Xamarin Workbooks
| Detail          | Value                       |
| :-------------- | :-------------------------- |
| Version         | 1.4.0-beta1                 |
| Git Branch      | master                      |
| Git Hash        | 2e30f47                     |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component       | Value                                      |
| :-------------- | :----------------------------------------- |
| Windows         | Microsoft Windows NT 10.0.16299.0 (64-bit) |
| CPU Cores       | 8                                          |
| Physical Memory | 16 GB                                      |

#### VisualStudio.15.Release Components
| Component                    | Version           |
| :--------------------------- | :---------------- |
| Visual Studio Community 2017 | 15.4.1+27004.2005 |
| Xamarin iOS                  | 11.2.0-8          |
| Xamarin Android              | 8.0.0-33          |

### Log File

[Xamarin Workbooks 2017-12-17.log](https://github.com/Microsoft/workbooks/files/1565510/Xamarin.Workbooks.2017-12-17.log)

**Comment by sandyarmstrong** [comment] 2017-12-18 15:36
This is a duplicate of https://github.com/Microsoft/workbooks/issues/118, so I'm closing.

Can you answer some quick questions for me?

1. Can you build and run a simple Android app from Visual Studio?
2. If you go to `Tools > Options > Xamarin > Android Settings`, what path do you see in `Android SDK Location`?
3. If you go to the path specified above, does it contain `tools` and `platform-tools` folders?

Thank you!

**Closed by sandyarmstrong** 2017-12-18 15:36 UTC

**Comment by CatoCensor** [comment] 2017-12-20 16:41
I already built android apps in visual studio and there is the platform-tools folder in the SDK path.
Thanks for the comment and sorry if I did not notice before.
