### ISSUE TITLE
upgraded workbooks & now it crashes on startup

### ISSUE THREAD

**Issue by CamelCaseMaster** [Microsoft/workbooks#488] opened 2018-07-07 12:08 UTC
### Steps to Reproduce

1. open working workbook
2. upgrade to latest stable version
3. crashes on startup

### Expected Behavior
opens up without crashing

### Actual Behavior
crashes on startup

### Environment
windows 7 64bit

### Log File

Xamarin Workbooks
Copyright 2016-2017 Microsoft. All rights reserved.
Copyright 2014-2016 Xamarin Inc. All rights reserved.
├─ Version: 1.4.0
├─ Date: 19/01/2018 23:00:55
├─ Hash: b3f92f9bf27419a6b57d06cafa2c2385b45f8d28
├─ Branch: master
└─ Lane: Workbooks & Inspector (Win)

[Info][00:00:00.2496004] ClientApp (Initialize): AppSessionId: 70003ac3-9cc0-42c2-a5c9-dd25d832c48a @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:112
[Info][00:00:09.4068165] WorkbookAppInstallation (LocateWorkbookApps): Loading workbook apps from manifest: C:\Program Files (x86)\Xamarin\Workbooks\WorkbookApps\workbookapps.json @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\WorkbookAppInstallation.cs:213
[Info][00:00:14.0410420] UpdaterService (CheckForUpdatesInBackground): checking for updates @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\Client\Updater\UpdaterService.cs:257
[Info][00:00:14.1502422] Telemetry (PostEventOnceAsync): Disabling telemetry at service's direction (403). @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\Telemetry\Client.cs:147
[Info][00:00:19.3537201] UpdaterService (CheckForUpdatesInBackground): update available: https://dl.xamarin.com/interactive/XamarinInteractive-1.4.2.msi @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\Client\Updater\UpdaterService.cs:269
[Info][00:06:45.8008237] UpdaterViewModel (StartDownloadAsync): download operation lasted 00:06:00.1247926 @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\Client\Updater\UpdaterViewModel.cs:161

Xamarin Workbooks
Copyright 2016-2017 Microsoft. All rights reserved.
Copyright 2014-2016 Xamarin Inc. All rights reserved.
├─ Version: 1.4.2
├─ Date: 05/07/2018 19:45:24
├─ Hash: 213565e1525257578d80ffe03b815572804d4005
├─ Branch: 1.4-release
└─ Lane: Workbooks & Inspector (Win)

[Info][00:00:00.0380022] ClientApp (Initialize): AppSessionId: 3f2d941c-f7be-4f7a-93a8-a93e76d9e107 @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:112
[Critical][00:00:00.7810447] ClientApp:AppDomain.UnhandledException (ConfigureLogging): exception: System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.OSPlatform Xamarin.Interactive.Runtime.get_OSPlatform()'.
   at Xamarin.Interactive.Telemetry.Client..ctor(Guid sessionid, HostEnvironment host, UpdaterService updater)
   at Xamarin.Interactive.ClientApp.Initialize(Boolean asSharedInstance, ILogProvider logProvider)
   at Xamarin.Interactive.Client.Windows.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xamarin.Interactive.Client.Windows.App.Main(String[] args) @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:204

Xamarin Workbooks
Copyright 2016-2017 Microsoft. All rights reserved.
Copyright 2014-2016 Xamarin Inc. All rights reserved.
├─ Version: 1.4.2
├─ Date: 05/07/2018 19:45:24
├─ Hash: 213565e1525257578d80ffe03b815572804d4005
├─ Branch: 1.4-release
└─ Lane: Workbooks & Inspector (Win)

[Info][00:00:00.0320018] ClientApp (Initialize): AppSessionId: 62e78bd0-7f39-4a0f-acbc-ac77daa612a5 @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:112
[Critical][00:00:00.1540088] ClientApp:AppDomain.UnhandledException (ConfigureLogging): exception: System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.OSPlatform Xamarin.Interactive.Runtime.get_OSPlatform()'.
   at Xamarin.Interactive.Telemetry.Client..ctor(Guid sessionid, HostEnvironment host, UpdaterService updater)
   at Xamarin.Interactive.ClientApp.Initialize(Boolean asSharedInstance, ILogProvider logProvider)
   at Xamarin.Interactive.Client.Windows.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xamarin.Interactive.Client.Windows.App.Main(String[] args) @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:204

Xamarin Workbooks
Copyright 2016-2017 Microsoft. All rights reserved.
Copyright 2014-2016 Xamarin Inc. All rights reserved.
├─ Version: 1.4.2
├─ Date: 05/07/2018 19:45:24
├─ Hash: 213565e1525257578d80ffe03b815572804d4005
├─ Branch: 1.4-release
└─ Lane: Workbooks & Inspector (Win)

[Info][00:00:00.0340019] ClientApp (Initialize): AppSessionId: d36ea5de-0e36-4faa-b4ce-e379cf285504 @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:112
[Critical][00:00:00.1630093] ClientApp:AppDomain.UnhandledException (ConfigureLogging): exception: System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.OSPlatform Xamarin.Interactive.Runtime.get_OSPlatform()'.
   at Xamarin.Interactive.Telemetry.Client..ctor(Guid sessionid, HostEnvironment host, UpdaterService updater)
   at Xamarin.Interactive.ClientApp.Initialize(Boolean asSharedInstance, ILogProvider logProvider)
   at Xamarin.Interactive.Client.Windows.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xamarin.Interactive.Client.Windows.App.Main(String[] args) @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:204

Xamarin Workbooks
Copyright 2016-2017 Microsoft. All rights reserved.
Copyright 2014-2016 Xamarin Inc. All rights reserved.
├─ Version: 1.4.2
├─ Date: 05/07/2018 19:45:24
├─ Hash: 213565e1525257578d80ffe03b815572804d4005
├─ Branch: 1.4-release
└─ Lane: Workbooks & Inspector (Win)

[Info][00:00:00.0360020] ClientApp (Initialize): AppSessionId: a05513fd-637e-4e0a-8e69-14fcbdb39e74 @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:112
[Critical][00:00:00.1680096] ClientApp:AppDomain.UnhandledException (ConfigureLogging): exception: System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.OSPlatform Xamarin.Interactive.Runtime.get_OSPlatform()'.
   at Xamarin.Interactive.Telemetry.Client..ctor(Guid sessionid, HostEnvironment host, UpdaterService updater)
   at Xamarin.Interactive.ClientApp.Initialize(Boolean asSharedInstance, ILogProvider logProvider)
   at Xamarin.Interactive.Client.Windows.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xamarin.Interactive.Client.Windows.App.Main(String[] args) @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:204

Xamarin Workbooks
Copyright 2016-2017 Microsoft. All rights reserved.
Copyright 2014-2016 Xamarin Inc. All rights reserved.
├─ Version: 1.4.2
├─ Date: 05/07/2018 19:45:24
├─ Hash: 213565e1525257578d80ffe03b815572804d4005
├─ Branch: 1.4-release
└─ Lane: Workbooks & Inspector (Win)

[Info][00:00:00.0330018] ClientApp (Initialize): AppSessionId: 11066983-cc42-4b4f-a3e9-997a5d4bf60b @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:112
[Critical][00:00:00.1510086] ClientApp:AppDomain.UnhandledException (ConfigureLogging): exception: System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.OSPlatform Xamarin.Interactive.Runtime.get_OSPlatform()'.
   at Xamarin.Interactive.Telemetry.Client..ctor(Guid sessionid, HostEnvironment host, UpdaterService updater)
   at Xamarin.Interactive.ClientApp.Initialize(Boolean asSharedInstance, ILogProvider logProvider)
   at Xamarin.Interactive.Client.Windows.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xamarin.Interactive.Client.Windows.App.Main(String[] args) @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:204

Xamarin Workbooks
Copyright 2016-2017 Microsoft. All rights reserved.
Copyright 2014-2016 Xamarin Inc. All rights reserved.
├─ Version: 1.4.2
├─ Date: 05/07/2018 19:45:24
├─ Hash: 213565e1525257578d80ffe03b815572804d4005
├─ Branch: 1.4-release
└─ Lane: Workbooks & Inspector (Win)

[Info][00:00:00.0370021] ClientApp (Initialize): AppSessionId: 9e48ea3c-335e-4436-8a96-3d3dcd59ab99 @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:112
[Critical][00:00:00.1700097] ClientApp:AppDomain.UnhandledException (ConfigureLogging): exception: System.MissingMethodException: Method not found: 'System.Runtime.InteropServices.OSPlatform Xamarin.Interactive.Runtime.get_OSPlatform()'.
   at Xamarin.Interactive.Telemetry.Client..ctor(Guid sessionid, HostEnvironment host, UpdaterService updater)
   at Xamarin.Interactive.ClientApp.Initialize(Boolean asSharedInstance, ILogProvider logProvider)
   at Xamarin.Interactive.Client.Windows.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Xamarin.Interactive.Client.Windows.App.Main(String[] args) @ C:\vsts\_work\5\s\Clients\Xamarin.Interactive.Client\ClientApp.cs:204

**Comment by sandyarmstrong** [comment] 2018-07-08 19:00
Hi @CamelCaseMaster, thanks so much for reporting this! Looks like we accidentally used newer .NET Framework APIs without updating the installer to indicate that. We'll fix that ASAP for other users on older versions of Windows.

For now, you can fix this on your own system by installing .NET Framework 4.7.1 (or newer) from https://www.microsoft.com/en-us/download/details.aspx?id=56115 .

**Comment by sandyarmstrong** [comment] 2018-07-08 22:44
Yeah this may actually be more complicated (https://github.com/dotnet/standard/issues/567). We'll do some testing tomorrow.

**Comment by sandyarmstrong** [comment] 2018-07-08 22:46
https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/510901-BCL%20Apps%20targeting%20.NET-4.6.1%20that%20use%20.NET%20Standard%20libraries%20might%20be%20broken%20when%20running%20on%20.NET%204.7.1.md implies that http://go.microsoft.com/fwlink/?LinkId=866028 should fix it for you.

**Comment by sandyarmstrong** [comment] 2018-07-08 23:35
In my quick testing, the problem is exactly what I linked above (a bug with .NET 4.7.1 framework).

Installing http://go.microsoft.com/fwlink/?LinkId=866028 definitely fixed it for me.

**Comment by sandyarmstrong** [comment] 2018-07-09 14:07
Well, it fixed the crash. There may be other issues. Will update again when we have a complete fix.

**Comment by CamelCaseMaster** [comment] 2018-07-09 20:23
Hi again!

1-I downloaded & tried to install the fix(NDP471-KB4054856-x86-x64-AllOS.exe) but I get this error: the Software update KB4054856 does not apply http://prntscr.com/k4glhr

2-I followed the troubleshooter & reinstalled .net package(NDP471-KB4033342-x86-x64-AllOS-ENU.exe just making sure. It went pretty fast) http://prntscr.com/k4gn03 

Tried to install the fix another time but ended up with the same error as 1. Maybe I'm missing something

**Comment by sandyarmstrong** [comment] 2018-07-09 20:36
That is very strange, but I'm not sure what would cause it. Can you check for recommended updates in Windows Update? According to https://blogs.msdn.microsoft.com/dotnet/2018/01/09/net-framework-4-7-1-is-available-on-windows-update-wsus-and-mu-catalog/ , this fix was distributed with .NET 4.7.1 for users that acquired it via Windows Update.

That being said, we are releasing a fixed installer very soon that should work on the version of .NET 4.7.1 that you have.

**Comment by sandyarmstrong** [comment] 2018-07-09 22:03
Fixed in 1.4.3.

**Closed by sandyarmstrong** 2018-07-09 22:03 UTC

**Comment by abock** [comment] 2018-07-09 22:11
@CamelCaseMaster this should be worked around in 1.4.3: https://github.com/Microsoft/workbooks/releases/download/v1.4.3/XamarinInteractive-1.4.3.msi
