### ISSUE TITLE
Undesired emoji rendered (possible wontfix)

### ISSUE THREAD

**Issue by Phrohdoh** [Microsoft/workbooks#491] opened 2018-08-27 16:23 UTC
### Steps to Reproduce

```csharp
public class Data
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public bool HasError { get; set; }
}

static List<Data> GenData(int count, Random rand)
    => Enumerable.Range(0, count)
       .Select(_ => new Data { HasError = rand.Next(0, 2) == 0 })
       .ToList();

var rand = new Random();
var batch = GenData(10, rand);
Console.WriteLine(batch.Select((b, idx) => $"{idx}: {b.Id} {b.HasError}"));
```

### Expected Behavior

The text is rendered.

### Actual Behavior

An emoji is rendered (yay web-tech everywhere?).

<img width="752" alt="webtech4lyfe" src="https://user-images.githubusercontent.com/4861023/44671476-336d2600-a9eb-11e8-82c7-d166504ebaa9.png">

#### Xamarin Workbooks
| Detail | Value |
| :- | :- |
| Version | 1.4.3 |
| Git Branch | 1.4-release |
| Git Hash | db27525 |
| VSTS Definition | Workbooks & Inspector (Mac) |

#### System Info
| Component | Value |
| :- | :- |
| macOS | Version 10.13.6 (Build 17G65) (64-bit) |
| CPU Cores | 8 / 8 |
| Physical Memory | 16 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Mono | 5.10.1.57 |
| Visual Studio | 7.5.2.40 (705020040) |

### Log File

<details>

```
Xamarin Workbooks
Copyright 2016-2018 Microsoft. All rights reserved.
Copyright 2014-2016 Xamarin Inc. All rights reserved.
├─ Version: 1.4.3
├─ Date: 7/9/2018 4:20:18 PM
├─ Hash: db27525ac40c50f7f96740bd037eb365515ed003
├─ Branch: 1.4-release
└─ Lane: Workbooks & Inspector (Mac)

[Info][00:00:00.0214120] ClientApp (Initialize): AppSessionId: f0c33806-063b-481f-947a-1233acbac80b @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/ClientApp.cs:112
[Info][00:00:00.1552740] Telemetry (.ctor): Telemetry is disabled @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/Telemetry/Client.cs:51
[Info][00:00:00.2967670] UpdaterService (CheckForUpdatesInBackground): checking for updates @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/Client/Updater/UpdaterService.cs:257
[Info][00:00:00.6645090] WorkbookAppInstallation (LocateWorkbookApps): Loading workbook apps from manifest: /Applications/Xamarin Workbooks.app/Contents/SharedSupport/WorkbookApps/workbookapps.json @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/WorkbookAppInstallation.cs:215
[Info][00:00:02.5392820] SessionDocument (ReadFromUrl): url: xamarin-interactive:///v1?agentType=DotNetCore&sessionKind=Workbook, typeName: com.xamarin.workbook @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client.Mac/SessionDocument.cs:123
[Info][00:00:02.7352960] SessionDocument (MakeWindowControllers): Created Xamarin.Interactive.Client.Mac.SessionWindowController @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client.Mac/SessionDocument.cs:66
[Info][00:00:02.8019340] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:00:02.8773780] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:00:03.4375420] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:00:03.5294520] UpdaterService (CheckForUpdatesInBackground): no updates are available @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/Client/Updater/UpdaterService.cs:267
[Info][00:00:03.6394780] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:00:03.9099470] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:00:04.3411070] MessageViewController (LogMessage): PushMessage => Status: Connecting to agent… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:00:00.2139300] DotNetCoreAgent (Start): DotNetCore 'Xamarin.Workbooks.DotNetCore' is available for interaction: xamarin-interactive://127.0.0.1:57075/v1?agentType=DotNetCore&sessionKind=Workbook @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:285
[Info][00:00:04.9800050] MessageViewController (LogMessage): PushMessage => Status: Preparing workspace… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:00:00.4344640] DotNetCoreAgent (ChangeDirectory): /Applications/Xamarin Workbooks.app/Contents/Resources → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
[Info][00:00:05.0729070] CompilationWorkspaceFactory (CreateDependencyResolver): Searching assembly path /Applications/Xamarin Workbooks.app/Contents/SharedSupport/WorkbookApps/DotNetCore/osx-x64/ @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/Compilation/CompilationWorkspaceFactory.cs:130
[Info][00:00:06.9444970] MessageViewController (LogMessage): PushMessage => Status: Restoring packages… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:00:07.0321090] InteractivePackageManager (.ctor): Enumerating NuGet source repositories @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:98
[Info][00:00:07.0497000] InteractivePackageManager (.ctor):     [nuget.org] https://api.nuget.org/v3/index.json (primary) @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:91
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:00:25.4286020] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:00:34.7806080] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:00:46.8419110] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
[Error][00:01:48.9122780] MonacoExtensions (ToMonacoPromise): exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Interactive.CodeAnalysis.Monaco.SignatureHelpProvider+<ComputeSignatureHelpAsync>d__9.MoveNext () [0x00161] in <1153f9c8c3d44a36b1c6bd2284901697>:0 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object
  at Xamarin.Interactive.CodeAnalysis.Monaco.SignatureHelpProvider+<ComputeSignatureHelpAsync>d__9.MoveNext () [0x00161] in <1153f9c8c3d44a36b1c6bd2284901697>:0 <---
 @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/CodeAnalysis/Monaco/MonacoExtensions.cs:71
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:03:40.8638390] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:04:25.9339190] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:05:13.2956930] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:05:19.2676240] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:07:10.3629680] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:08:29.4474200] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:08:29.5006820] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:08:36.6152840] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
[Info][00:11:32.1841420] SessionDocument (ReadFromUrl): url: xamarin-interactive:///v1?agentType=DotNetCore&sessionKind=Workbook, typeName: com.xamarin.workbook @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client.Mac/SessionDocument.cs:123
[Info][00:11:32.2299410] SessionDocument (MakeWindowControllers): Created Xamarin.Interactive.Client.Mac.SessionWindowController @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client.Mac/SessionDocument.cs:66
[Info][00:11:32.2454920] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:11:32.2576390] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:11:32.9583270] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:11:32.9834530] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:11:33.0811180] MessageViewController (LogMessage): PushMessage => Status: Loading workbook… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:11:33.1696250] MessageViewController (LogMessage): PushMessage => Status: Connecting to agent… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:11:33.3625060] MessageViewController (LogMessage): PushMessage => Status: Preparing workspace… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:11:28.8078090] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
[Info][00:11:33.4492960] CompilationWorkspaceFactory (CreateDependencyResolver): Searching assembly path /Applications/Xamarin Workbooks.app/Contents/SharedSupport/WorkbookApps/DotNetCore/osx-x64/ @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/Compilation/CompilationWorkspaceFactory.cs:130
[Info][00:11:34.6005820] MessageViewController (LogMessage): PushMessage => Status: Restoring packages… @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Messages/MessageViewController.cs:129
[Info][00:11:34.6067690] InteractivePackageManager (.ctor): Enumerating NuGet source repositories @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:98
[Info][00:11:34.6077900] InteractivePackageManager (.ctor):     [nuget.org] https://api.nuget.org/v3/index.json (primary) @ /Users/builder/vsts-agent/_work/2/s/Clients/Xamarin.Interactive.Client/NuGet/InteractivePackageManager.cs:91
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:13:25.6630330] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
Xamarin.Workbooks.DotNetCore (127.0.0.1:57075) => [Info][00:15:16.7968150] DotNetCoreAgent (ChangeDirectory): /private/var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T → /var/folders/fg/bqms9ck51q5dnfdl1nrw7ncc0000gp/T/ @ /Users/builder/vsts-agent/_work/2/s/Agents/Xamarin.Interactive/Core/Agent.cs:333
```

</details>

---

This is probably a good candidate for a `wontfix` resolution because how would you know when to render the raw text vs rendering an emoji.

**Comment by sandyarmstrong** [comment] 2018-08-27 17:28
What text do you expect to be rendered? Try your same code in a standard console project and you'll get a similar result (no 🐵 since it's not inside a workbook, though). You are seeing the result of running `List<Data>.Select(...).ToString()`, which is not going to be meaningful, as it just prints the type itself.

Remove the `Console.WriteLine`, and Workbooks will actually render an interactive enumerable that is probably more like what you're looking for. For example:

![image](https://user-images.githubusercontent.com/155076/44674946-eafe3a00-a9e3-11e8-9ada-17222169bc4d.png)

**Comment by sandyarmstrong** [comment] 2018-08-27 17:30
Closing for now, but feel free to reopen if I've misunderstood your issue. The 🐵 just represents the hidden class the workbook code executes within. You see it because it's part of the fully-qualified type name of your `Data` class.

**Closed by sandyarmstrong** 2018-08-27 17:30 UTC

**Comment by Phrohdoh** [comment] 2018-08-27 17:55
I'm pretty sure the 🐵 emoji isn't part of the class name but is how the text is being interpreted, that was the point of the ticket. :)

**Comment by sandyarmstrong** [comment] 2018-08-27 18:03
The 🐵 is part of the fully-qualified name of every type that is defined in a workbook. See below:

![image](https://user-images.githubusercontent.com/155076/44676657-bfca1980-a9e8-11e8-87c6-07c1d93463ac.png)

**Comment by Phrohdoh** [comment] 2018-08-27 18:04
Oh I did not know that... interesting!
I understand now.

I had assumed this was a unicode escape sequence being rendered instead of printed as text.

**Comment by abock** [comment] 2018-08-28 16:35
Yep, [this is by design](https://github.com/Microsoft/workbooks/blob/master/CodeAnalysis/Xamarin.Interactive.CodeAnalysis.Roslyn/RoslynCompilationWorkspace.cs#L513), and it gets more interesting.

Roslyn generates a "shell" class for each cell/submission when using script mode compilation. We intentionally name this shell class with a prefix (`🐵BEAR`)<sup>1, 2, 3</sup> and some metadata that changes on each execution iteration of the submission.

In the context of Roslyn scripting, "local variables" are actually fields on this implied type. Similarly, "functions" are methods on the type, and any types you define within a cell are simply nested classes, structs, interfaces, enums, etc. therein.

Further, there is a 1:1 relation with this shell class to the _assembly_ that hosts it. After we compile the cell, we remote the generated assembly, which has the same name as the shell class, to the execution environment that should run it (the iOS, Android, Mac, .NET Framework, .NET Core, etc. runtime).

And thus, the variable metadata is necessary to work around a [design issue regarding assembly loading in the Mono runtime](https://github.com/Microsoft/workbooks/blob/master/CodeAnalysis/Xamarin.Interactive.CodeAnalysis.Roslyn/MonoScriptCompilationPatcher.cs), so that each version of a cell results in the loading of differently named assembly. The issue in Mono ([which was recently fixed in `master`](https://github.com/mono/mono/pull/8821)) is that it would refuse to reload an assembly _with the same name_. When the version of Mono that is fixed makes its way into all of the Xamarin SDKs, we can actually remove a ton of code from Workbooks that works around it.

-----

#### Fun Facts ####

1. [We used to patch the four bytes that `🐻`](https://github.com/Microsoft/workbooks/commit/57a0a186553cf42ec80fceb3da39dc43af285636#diff-b940b418d91c5aa1473fce8fb4a9e450) occupied from our original prefix (`🐵🐻`) as the unique value, but had to change it recently to `🐵BEAR` [due to a regression in .NET Core 2.1.300](https://github.com/dotnet/coreclr/issues/18269).

2. `🐵` was chosen as an homage to Xamarin, Mono, Ximian, Helix Code, etc. Everything is monkey themed with us. Roslyn's `csi` uses `ℛ` as a prefix.

3. `BEAR` (or the original `🐻`) because the first letter of the last names of @abock, @lewing, @sandyarmstrong and @bojanrajkovic, the four primary Workbooks devs, can be arranged to spell... BEAR.
