### ISSUE TITLE
Package dialog hangs after locking/unlocking the machine

### ISSUE THREAD

**Issue by jkotas** [Microsoft/workbooks#115] opened 2017-12-01 17:41 UTC
### Environment

**[Log File](https://github.com/Microsoft/workbooks/files/1522412/Xamarin.Inspector.2017-12-01.log)

### Steps to Reproduce

1. Create default .NET Framework workbook
2. Lock the machine (Windows Key + L), login again
3. Select "Add package" from menu

### Expected Behavior

Add package dialog shows up

### Actual Behavior

Blue shadow of the package dialog shows up, the app becomes unresponsive

![image](https://user-images.githubusercontent.com/6668460/33495324-c814b100-d67a-11e7-8529-8dab73005333.png)

**Comment by bojanrajkovic** [comment] 2017-12-01 18:22
I've seen this once or twice before, but could not find a reliable reproduction until now. Thanks for the information, will take a look at this.

**Comment by bojanrajkovic** [comment] 2017-12-01 18:36
This looks like https://github.com/MahApps/MahApps.Metro/issues/2734 -- we're on a pretty old MahApps, 1.3.0.

**Comment by bojanrajkovic** [comment] 2017-12-01 18:57
Thanks again for the report and the great reproduction steps! Will be fixed in the next 1.4 release via #116.

**Closed** 2017-12-04 20:20 UTC
Labels: Area: Shell, Bug, Windows
